version: "3.8"
services:
  app:
    build: .
    working_dir: /app
    environment:
      - PIPELINE_VERSION=0.1.0
      - LOG_LEVEL=INFO
      - LANGUAGE=en
      - TOKEN_CAP_PER_STEP=140
      - NEAR_DUPLICATE_COSINE=0.9
      - USE_LOCAL_LLM=true
      - LOCAL_LLM_ENDPOINT=http://host.docker.internal:11434/api/generate
      - LOCAL_LLM_MODEL=qwen2.5:3b-instruct
      - LLM_TEMPERATURE=0.3
    volumes:
      - ./:/app
    command: ["pytest", "-q"]

  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     - POSTGRES_USER=lesson
  #     - POSTGRES_PASSWORD=lesson
  #     - POSTGRES_DB=lesson
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}


